# Generated by Django 3.2.15 on 2022-10-31 01:06

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20220128_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_preset_color', models.CharField(blank=True, choices=[('grey', 'Grey'), ('blue', 'Blue'), ('light-blue', 'Light Blue'), ('red', 'Red'), ('green', 'Green'), ('violet', 'Violet'), ('purple', 'Purple')], max_length=100, null=True)),
                ('background_custom_color', colorfield.fields.ColorField(blank=True, default='#B7B7B7', image_field=None, max_length=18, null=True, samples=None)),
                ('background_preset_image', models.CharField(blank=True, choices=[('transparency', 'Default (solid grey)'), ('weave', 'Weave'), ('boxes', 'Boxes')], max_length=100, null=True)),
                ('background_custom_image', models.ImageField(blank=True, null=True, upload_to='usercontent/backgrounds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
