# Generated by Django 3.2.15 on 2022-10-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='background_preset_image',
            field=models.CharField(blank=True, choices=[('ps_neutral', 'Default (solid grey)'), ('pixel_weave', 'Weave'), ('pw_pattern', 'Boxes')], max_length=100, null=True),
        ),
    ]
