# Generated by Django 3.2.15 on 2022-10-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_theme_background_preset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='background_custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='usercontent/backgrounds/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
