# Generated by Django 3.2.15 on 2022-10-31 02:33

from django.db import migrations, models
import intranet.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_theme_background_custom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='background_custom_image',
            field=models.ImageField(blank=True, null=True, upload_to=intranet.apps.users.models.custom_user_background_upload_path),
        ),
    ]
